Useit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include ('apps.usuario.urls', namespace="usuario")),
    path('registros/', include ('apps.registro.urls', namespace="registro")),

    path('accounts/login/', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/reset/password_reset', auth_views.PasswordResetView.as_view(), name= 'password_reset'),
    #auth_views.PasswordResetForm.as_view(),
    path('accounts/reset/password_reset_confirm', auth_views.PasswordChangeDoneView.as_view(), name= 'password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name= 'password_reset_confirm'),
    path('accounts/reset/done', auth_views. PasswordResetCompleteView.as_view(), name= 'password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuario/urls.py
from django.urls import path, include
from .views import RegistroUsuario, PagPrincipal, ProfileUpdate
app_name= "Hola"
urlpatterns = [

path('registro/usuario', RegistroUsuario.as_view(),name='usuario_registro'),

path('inicio', PagPrincipal.as_view(),name='inicio'),

path('profile/', ProfileUpdate.as_view(), name="profile" )





]

templates/login/login.html
<!DOCTYPE html>

{% load static %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Prueba - Login</title>

  {% if 'register' in request.GET %}
  <p style= "color:white;"> Usuario Registrado Correctamente, ya puedes identificarte  </p>

  {% endif %}

  {% if form.errors %}
  <script>
  alert('Tu usuario o contraseña no es correcta. Intenta nuevamente')
</script>

  {% endif %}

  <!-- Custom fonts for this template-->
  <link rel="shortcut icon" type="image/png" href="{% static 'logo.png' %}"/>
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %} " rel="stylesheet" type="text/css">
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <img src="{% static 'logo.png' %}" width="500" height="500" class="col-lg-6 d-none d-lg-block " alt="NutriPay">

              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Bienvenido de Nuevo! </h1>
                  </div>
                  <form method="post" class="user">
                     {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" name="username" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Ingrese nombre de Usuario...">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" name="password" id="exampleInputPassword" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                          <input class="btn btn-primary btn-user btn-block" type="submit" value="Ingresar">
                      </div>
                    </div>
                    <a >


                    </a>
                    <hr>
                    <a href="index.html" class="btn btn-google btn-user btn-block">
                      <i class="fab fa-google fa-fw"></i> Login with Google
                    </a>
                    <a href="index.html" class="btn btn-facebook btn-user btn-block">
                      <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                    </a>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'password_reset' %}">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'usuario:usuario_registro'%}">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>




  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>


</body>

</html>

templates/login/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Register</title>
<!--
  {% if form.errors %}
  <script>
  alert('Tu usuario o contraseña no es correcta. Intenta nuevamente')
</script>

  {% endif %}
-->

  <!-- Custom fonts for this template-->
  <link rel="shortcut icon" type="image/png" href="{% static 'logo.png' %}"/>
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %} " rel="stylesheet" type="text/css">
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->



</head>



<body class="bg-gradient-primary">

  <div class="container">


    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">

        <!-- Nested Row within Card Body -->
        <div class="row">

          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
              </div>
              <form class="user" method="post">
                	{% csrf_token %}



                  <div class="form-group row">




                  </div>

                  <div class="form-group ">




                  </div>









               <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                      {{ form.first_name }}
                  </div>
                  <div class="col-sm-6">
                          {{form.last_name}}
                  </div>
                </div>
                <div class="form-group">
                    {{ form.username }}
                </div>
                <div class="form-group">
                    {{form.email }}
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                      {{form.password1 }}
                        {{ field.errors }}
                  </div>
                  <div class="col-sm-6">
                    {{form.password2 }}
                      {{ field.errors }}
                  </div>
                </div>
                <div class="form-group">
			        	<button class="btn btn-primary btn-user btn-block "type="submit">Guardar</button>
		           	</div>

              </form>

        {% if form.errors %}
        <p style= "color:red;"> No podemos procesar tu solicitud, por los siguientes errores :  </p>
              {% for field in form %}
      <div class="fieldWrapper">

          {{ field.errors }}
      </div>
  {% endfor %}
  {% endif %}

                <hr>
                <a href="index.html" class="btn btn-google btn-user btn-block">
                  <i class="fab fa-google fa-fw"></i> Register with Google
                </a>
                <a href="index.html" class="btn btn-facebook btn-user btn-block">
                  <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                </a>

              <hr>
              <div class="text-center">
                <a class="small" href="forgot-password.html">Forgot Password?</a>
              </div>
              <div class="text-center">
                <a class="small" href="login.html">Already have an account? Login!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>




  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>




  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>


</body>

</html>