Useit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include ('apps.usuario.urls', namespace="usuario")),
    path('registros/', include ('apps.registro.urls', namespace="registro")),

    path('accounts/login/', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/reset/password_reset', auth_views.PasswordResetView.as_view(), name= 'password_reset'),
    #auth_views.PasswordResetForm.as_view(),
    path('accounts/reset/password_reset_confirm', auth_views.PasswordChangeDoneView.as_view(), name= 'password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name= 'password_reset_confirm'),
    path('accounts/reset/done', auth_views. PasswordResetCompleteView.as_view(), name= 'password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/registro/urls.py
from django.urls import path, include
from .views import EventListView, Event_Create, EventUpdate, asisir_events, rechazar_events, interesados_list, Event_Delete, confirm_events, rechaza_list, confirma_list, interesados_list
from django.contrib.auth.decorators import login_required


app_name= "Hola2"
urlpatterns = [

    path('crear/', login_required(Event_Create.as_view()),name='crear'),
    path('lista', EventListView.as_view(),name='lista'),
    path('editar/<int:pk>/', EventUpdate.as_view(),name='editar'),
    path('eliminar/<int:pk>/', Event_Delete.as_view(),name='eliminar'),
    path('asisir_events/<int:id_page>/', asisir_events ,name='asiste'),
    path('rechazar_events/<int:id_page>/', rechazar_events ,name='rechaza'),
    path('confima_events/<int:id_page>/', confirm_events ,name='confirma'),

    path('intereses/', interesados_list ,name='intereses'),
    path('confirmados/', confirma_list ,name='confirmados'),
    path('rechazados/', rechaza_list ,name='rechazados'),






]

apps/registro/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
import time
from django.utils import timezone



# Create your models here.



class Registros(models.Model):

    titulo= models.CharField(max_length=50)
    image = models.ImageField(upload_to='profiles', null=True, blank=True)
    descripcion= models.CharField(max_length=82)
    Tipos=(('Publico','Publico'),('Privado','Privado'))
    tipo=models.CharField(choices=Tipos,default="Publico",max_length=7)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
    interested_in = models.ManyToManyField(User,related_name="users_interested", blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="events", blank=True, null=True)
    not_interested_in = models.ManyToManyField(User,related_name="users_not_interested", blank=True)
    signed_up = models.ManyToManyField(User,related_name="users_assistants", blank=True)
    def __str__(self):
        return '{} '.format(self.id)

#    def save(self,*args, **kwargs):
    #    self.created_by=user.get_id
    #    return super(Transaccion, self).save( *args, **kwargs)





class Comment(models.Model):
    post = models.ForeignKey(Registros, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="eventsc")
    approved_comment = models.BooleanField(default=True)

apps/usuario/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='profiles', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['user__username']

apps/registro/forms.py
from django import forms
from .models import Registros
#from .models import TipoCuenta



class EventForm(forms.ModelForm):



    class Meta:
        model = Registros

        fields = [

        'titulo',
        'image',
        'descripcion',
        'tipo',
        'created_by',


        ]
        labels = {
                'titulo': 'Titulo' ,
                'image': 'Imagen del evento' ,
                'descripcion': 'Descripción' ,
                'tipo': 'Tipo' ,
                'created_by': 'Autor ' ,





        }
        widgets= {
                'titulo': forms.TextInput(attrs= {'class': 'form-control'}  )  ,

                'descripcion':   forms.TextInput(attrs= {'class': 'form-control'}  ) ,


        }

apps/registro/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from .models import Registros
from apps.registro.forms import EventForm
from apps.registro.models import Registros
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import render, redirect




@method_decorator(login_required, name='dispatch')
class Event_Create(LoginRequiredMixin,CreateView):
    model= Registros
    form_class = EventForm
    success_url= reverse_lazy('registro:lista')
    template_name='registro/create_event.html'
    def get_initial(self):
        initial = super().get_initial()
        initial['created_by'] = self.request.user.id
        return initial





class EventListView(ListView):
    model= Registros
    paginate_by =2

class Event_Update(UpdateView):
    model= Registros
    template_name='usuarios/usuarios_form.html'
    success_url= reverse_lazy('usuarios:usuario_listas')




class Event_Delete(DeleteView):
    model= Registros
    template_name='registro/borrar_registro.html'
    success_url= reverse_lazy('registro:lista')





@method_decorator(login_required, name='dispatch')
class EventUpdate(LoginRequiredMixin,UpdateView):
    model= Registros
    template_name= 'registro/edit_event.html'
    form_class= EventForm
    success_url= reverse_lazy('registro:lista')


def asisir_events(request,id_page):



    solicitud="Intereses"
    Evento = Registros.objects.get(id=id_page)
    user1 = User.objects.get(id=request.user.id)

    print("EVENTO",Evento)
    print("USUARIO",user1)
    queryset1 = Registros.objects.filter(
    Q(interested_in__username=request.user.username))
    print("  ESTA INTERESADO EN ESTOS ",queryset1)


    #Q(interested_in__username=request.user.username)&
    #Q(id=id_page))
    #print("  ESTA INTERESADO EN ESTOS ",queryset1)
    #print(Evento)
    #print(user1)
    Evento.interested_in.add(user1)
    Evento.not_interested_in.remove(user1)
    Evento.signed_up.remove(user1)





#    queryset2 = Registros.objects.filter(
#    Q(interested_in__username=id_page) ==
#    request.user.username
#    )


#    print("  si el mismo esta interesado en este evento  ",queryset2)

    return render(request, 'eventos/intereses_list.html', {'queryset1':queryset1, 'solicitud':solicitud } )



def rechazar_events(request,id_page):



    solicitud="Rechazados"
    Evento = Registros.objects.get(id=id_page)
    user1 = User.objects.get(id=request.user.id)

    print("EVENTO",Evento)
    print("USUARIO",user1)
    queryset1 = Registros.objects.filter(
    Q(not_interested_in__username=request.user.username))
    print("  ESTA INTERESADO EN ESTOS ",queryset1)


    #Q(interested_in__username=request.user.username)&
    #Q(id=id_page))
    #print("  ESTA INTERESADO EN ESTOS ",queryset1)
    #print(Evento)
    #print(user1)
    Evento.not_interested_in.add(user1)
    Evento.interested_in.remove(user1)
    Evento.signed_up.remove(user1)






#    queryset2 = Registros.objects.filter(
#    Q(interested_in__username=id_page) ==
#    request.user.username
#    )


#    print("  si el mismo esta interesado en este evento  ",queryset2)

    return render(request, 'eventos/intereses_list.html', {'queryset1':queryset1,'solicitud':solicitud } )



def confirm_events(request,id_page):



    solicitud="Confirmados"
    Evento = Registros.objects.get(id=id_page)
    user1 = User.objects.get(id=request.user.id)

    print("EVENTO",Evento)
    print("USUARIO",user1)
    queryset1 = Registros.objects.filter(
    Q(signed_up__username=request.user.username))
    print("  ESTA INTERESADO EN ESTOS ",queryset1)


    #Q(interested_in__username=request.user.username)&
    #Q(id=id_page))
    #print("  ESTA INTERESADO EN ESTOS ",queryset1)
    #print(Evento)
    #print(user1)
    Evento.signed_up.add(user1)
    Evento.not_interested_in.remove(user1)
    Evento.interested_in.remove(user1)


    return render(request, 'eventos/intereses_list.html', {'queryset1':queryset1,'solicitud':solicitud } )














def interesados_list(request):
    solicitud="Intereses"
    queryset1 = Registros.objects.filter(
    Q(interested_in__username=request.user.username))
    print("  ESTA INTERESADO EN ESTOS ",queryset1)

    #Evento.interested_in.add(user1)


#    queryset2 = Registros.objects.filter(
#    Q(interested_in__username=id_page) ==
#    request.user.username
#    )


#    print("  si el mismo esta interesado en este evento  ",queryset2)

    return render(request, 'eventos/intereses_list.html', {'queryset1':queryset1,'solicitud':solicitud  })


def confirma_list(request):
    solicitud="Confirmados"
    queryset1 = Registros.objects.filter(
    Q(signed_up__username=request.user.username))
    print("  ESTA INTERESADO EN ESTOS ",queryset1)

    #Evento.interested_in.add(user1)


#    queryset2 = Registros.objects.filter(
#    Q(interested_in__username=id_page) ==
#    request.user.username
#    )


#    print("  si el mismo esta interesado en este evento  ",queryset2)

    return render(request, 'eventos/intereses_list.html', {'queryset1':queryset1,'solicitud':solicitud })


def rechaza_list(request):
    solicitud="Rechazados"
    queryset1 = Registros.objects.filter(
    Q(not_interested_in__username=request.user.username))
    print("  ESTA INTERESADO EN ESTOS ",queryset1)

    #Evento.interested_in.add(user1)


#    queryset2 = Registros.objects.filter(
#    Q(interested_in__username=id_page) ==
#    request.user.username
#    )


#    print("  si el mismo esta interesado en este evento  ",queryset2)

    return render(request, 'eventos/intereses_list.html', {'queryset1':queryset1,'solicitud':solicitud })

apps/registro/templates/registro/borrar_registro.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
  <h3>¿Desea eliminar el registro {{object.titulo }}  </h3>

	<button class="btn btn-danger " type="submit">Si, eliminar</button>
  <a class="btn btn-default" href="{% url 'registro:lista' %}">Cancelar</a>


</form>
{% endblock %}

apps/registro/templates/registro/create_event.html
{% extends 'base/base.html' %}



{% block content %}
<style>.errorlist{color:red;} </style>
<main role="main">
  <div class="container">
    <div class="row mt-3 mb-5">
      <div class="col-md-9 mx-auto ">
          <h3>Perfil   {{ user.get_username }}</h3>

        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
          <div class="row">
            <!-- Previa del avatar -->

         <div class="text-center">
          {{form.as_p}}

            <!-- Formulario -->

            <!--  <input type="file" name="avatar" class="form-control-file mt-3" id="id_avatar"> -->

              <input type="submit" class="btn btn-primary btn-block" value="Actualizar">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

apps/registro/templates/registro/edit_event.html
{% extends 'base/base.html' %}



{% block content %}
<style>.errorlist{color:red;} </style>
<main role="main">
  <div class="container">
    <div class="row mt-3 mb-5">
      <div class="col-md-9 mx-auto ">
          <h3>Perfil   {{ user.get_username }}</h3>

        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
          <div class="row">
            <!-- Previa del avatar -->

         <div class="text-center">
          {{form.as_p}}

            <!-- Formulario -->

            <!--  <input type="file" name="avatar" class="form-control-file mt-3" id="id_avatar"> -->

              <input type="submit" class="btn btn-primary btn-block" value="Actualizar">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

apps/registro/templates/registro/registros_list.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load static %}







      {% block content %}

      <!-- End of Main Content -->
<br>
{% for page in object_list %}
        <div class="evento">
          <div class="item-evento imagen ">
            {% if page.image %}
            <img src="{{page.image.url}}" alt="" width="100%" height="100%">
            {% endif %}
          </div>
          <div class="item-evento información">

            <div class="item-información mas-info">
              <div class="item-mas-info detalles">

                <div id="nombre">
                  {{page.titulo}}
                </div>
                <div id="descripción">
                  {{page.descripcion}}
                </div>
                <div id="fecha">
               Creado el : {{page.created}}   Por : {{page.created_by.username}}
                </div>
              </div>
              <div class="item-mas-info editar">

                {%  if page.created_by.username == user.get_username %}
                <div class="text-center">
                |  <a class="btn btn-primary " href="{% url  'registro:editar' page.id  %}">Editar</a>
                |  <a class="btn btn-danger " href="{% url  'registro:eliminar' page.id  %}">Eliminar</a>
                {% else %}
                |  <a class="btn btn btn-primary  " disabled >Editar</a>
                |  <a class="btn btn-danger btn-disabled " disabled>Eliminar</a>
                {% endif %}
              </div>
              </div>
            </div>
            <div class="item-información acciones">
              <div class="item-acciones " id="asistir"><a class="btn btn-success " href="{% url  'registro:confirma' page.id  %}"> Asistir </a></div>
              <div class="item-acciones" id="interesado"><a class="btn btn-warning" href="{% url  'registro:asiste' page.id  %}"> Interesado </a></div>
              <div class="item-acciones" id="rechazar"><a class="btn btn-danger" href="{% url  'registro:rechaza' page.id  %}"> Rechazar </a></div>
            </div>
          </div>
        </div>

        <br>
        <br>

        {% endfor %}

        <!-- Menú de paginación -->
{% if is_paginated %}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item ">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">&laquo;</a>
        </li>
      {% endif %}
      {% for i in paginator.page_range %}
        <li class="page-item {% if page_obj.number == i %}active{% endif %}">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item ">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">&raquo;</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}



      {%  endblock  %}


      {% block footer %}





  {% endblock %}